// cspell:ignore Menya ussd USSD ibibazo by'ibishyimbo by'ibimera Ururimi Hitamo igihingwa ushaka kumenya Ibigori Imbogoro Imboga zijyanye Ibijumba Igenamiterere Gusuzuma ikibazo ifoto yawe Ikibazo Cyabonetse Ibisubizo Igihingwa Ikibazo Ubusubizo Sangiza kuri kibazo cy'ibimera nasuzumye kuri Menya Sangiza Ibisubizo Byasangijwe Ibisubizo byasangijwe neza Ikosa gusangiza ibisubizo ussd Fungura USSD ussd Kode USSD ussd Abahinzi cyaro fungura kode USSD kugira ubone ubufasha bw'inyongera Yego Ikosa Isuzuma Rishya Amateka y'Isuzuma mateka y'isuzuma arakorwa Siba Amateka Amateka yasibwe Menya Identifiez facilement problèmes feuilles plantes Sélectionnez Maïs Légumes verts Patates douces Paramètres problème Traitement votre Problème trouvé Résultats Problème Partager Découvrez plante identifié avec Partager Partagé partagés avec succès Erreur lors partage Obtenir agriculteurs ruraux composez Erreur analyse Historique Aucun historique d'analyse l'historique Historique effacé
const strings = {
  en: {
    appName: 'Menya Leaf AI',
    welcome: 'Identify plant leaf problems easily',
    language: 'Language',
    selectCrop: 'Select the crop you want to identify:',
    crops: {
      maize: 'Maize',
      cassava: 'Cassava',
      greenVegetables: 'Green Vegetables',
      sweetPotatoes: 'Sweet Potatoes',
    },
    settings: 'Settings',
    identifying: 'Identifying Problem...',
    processing: 'Processing your image...',
    problemFound: 'Problem Found',
    results: 'Identification Results',
    crop: 'Crop',
    problem: 'Problem',
    solution: 'Solution',
    shareWhatsApp: 'Share via WhatsApp',
    shareMessage: 'Check out this plant problem I identified with Menya Leaf AI!',
    shareTitle: 'Share Results',
    shared: 'Shared!',
    sharedMessage: 'Results shared successfully.',
    shareError: 'Error sharing results.',
    ussdCode: 'Get Help via USSD',
    ussdTitle: 'USSD Code',
    ussdMessage: 'For rural farmers, dial this USSD code for more help:',
    ok: 'OK',
    error: 'Error',
    newScan: 'New Scan',
    history: 'Scan History',
    noHistory: 'No scan history yet.',
    clearHistory: 'Clear History',
    historyCleared: 'History cleared.',
  },
  rw: {
    appName: 'Menya Leaf AI',
    welcome: 'Menya ibibazo by\'ibishyimbo by\'ibimera',
    language: 'Ururimi',
    selectCrop: 'Hitamo igihingwa ushaka kumenya:',
    crops: {
      maize: 'Ibigori',
      cassava: 'Imbogoro',
      greenVegetables: 'Imboga zijyanye',
      sweetPotatoes: 'Ibijumba',
    },
    settings: 'Igenamiterere',
    identifying: 'Gusuzuma ikibazo...',
    processing: 'Gusuzuma ifoto yawe...',
    problemFound: 'Ikibazo Cyabonetse',
    results: 'Ibisubizo',
    crop: 'Igihingwa',
    problem: 'Ikibazo',
    solution: 'Ubusubizo',
    shareWhatsApp: 'Sangiza kuri WhatsApp',
    shareMessage: 'Reba iki kibazo cy\'ibimera nasuzumye kuri Menya Leaf AI!',
    shareTitle: 'Sangiza Ibisubizo',
    shared: 'Byasangijwe!',
    sharedMessage: 'Ibisubizo byasangijwe neza.',
    shareError: 'Ikosa mu gusangiza ibisubizo.',
    ussdCode: 'Fungura USSD',
    ussdTitle: 'Kode ya USSD',
    ussdMessage: 'Abahinzi bo mu cyaro, fungura iyi kode ya USSD kugira ngo ubone ubufasha bw\'inyongera:',
    ok: 'Yego',
    error: 'Ikosa',
    newScan: 'Isuzuma Rishya',
    history: 'Amateka y\'Isuzuma',
    noHistory: 'Nta mateka y\'isuzuma arakorwa.',
    clearHistory: 'Siba Amateka',
    historyCleared: 'Amateka yasibwe.',
  },
  fr: {
    appName: 'Menya Leaf AI',
    welcome: 'Identifiez facilement les problèmes des feuilles de plantes',
    language: 'Langue',
    selectCrop: 'Sélectionnez la culture à identifier:',
    crops: {
      maize: 'Maïs',
      cassava: 'Manioc',
      greenVegetables: 'Légumes verts',
      sweetPotatoes: 'Patates douces',
    },
    settings: 'Paramètres',
    identifying: 'Identification du problème...',
    processing: 'Traitement de votre image...',
    problemFound: 'Problème trouvé',
    results: 'Résultats d\'identification',
    crop: 'Culture',
    problem: 'Problème',
    solution: 'Solution',
    shareWhatsApp: 'Partager via WhatsApp',
    shareMessage: 'Découvrez ce problème de plante que j\'ai identifié avec Menya Leaf AI!',
    shareTitle: 'Partager les résultats',
    shared: 'Partagé!',
    sharedMessage: 'Résultats partagés avec succès.',
    shareError: 'Erreur lors du partage des résultats.',
    ussdCode: 'Obtenir de l\'aide via USSD',
    ussdTitle: 'Code USSD',
    ussdMessage: 'Pour les agriculteurs ruraux, composez ce code USSD pour plus d\'aide:',
    ok: 'OK',
    error: 'Erreur',
    newScan: 'Nouvelle analyse',
    history: 'Historique des analyses',
    noHistory: 'Aucun historique d\'analyse pour le moment.',
    clearHistory: 'Effacer l\'historique',
    historyCleared: 'Historique effacé.',
  },
};
